# TODO THIS IS BROKEN FIX IT!!!!!!!!!!
# matrix:
#   platform:
#     - linux/arm64
#     - linux/amd64

# platform: ${platform}

labels:
  platform: linux/amd64

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.catvibers.me/aa/website-docker
      registry: git.catvibers.me
      # platforms: ${platform}
      platforms: linux/arm64,linux/amd64
      tags: latest
      dry-run: true
    when:
      event: [push, pull_request]

  deploy:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.catvibers.me/aa/website-docker
      registry: git.catvibers.me
      tags: latest
      # platforms: ${platform}
      platforms: linux/arm64,linux/amd64
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    when:
      event: [deployment]